repos:
- repo: local
  hooks:
  - id: document
    name: run devtools::document() before committing
    language: system
    entry: make -C minisparra doc
    always_run: true
    pass_filenames: false
