repos:
- repo: local
  hooks:
  - id: document
    name: Make sure functions have been documented
    language: system
    entry: make -C eider doc
    always_run: true
    pass_filenames: false

  - id: test
    name: Run tests
    language: system
    entry: make -C eider test
    always_run: true
    pass_filenames: false

  - id: lint
    name: Lint source code
    language: system
    entry: make -C eider lint
    always_run: true
    pass_filenames: false
