repos:
- repo: local
  hooks:
  - id: document
    name: Make sure functions have been documented and README generated
    language: system
    entry: make doc
    always_run: true
    pass_filenames: false

  - id: test
    name: Run tests
    language: system
    entry: make test
    always_run: true
    pass_filenames: false

  - id: lint
    name: Lint source code
    language: system
    entry: make lint
    always_run: true
    pass_filenames: false
