---
title: "Logging Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Logging Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(eider)
```

## Errors with context

Here are some examples of errors with context using the A&E data

```{r}
#filenames <- c("../example_data/random_ae_data.csv")
#all_tables <- read_all_tables(filenames)
#all_tables$`../example_data/random_ae_data.csv` %>% kbl()
```

### Example 1

```{r}
#lines <- readLines("./ae2_data_wrong1.json")
#lines[3]
```

```{r error=TRUE}
#transform(
#  all_table_filenames = all_table_filenames,
#  all_feature_json_filenames = "./ae2_data_wrong1.json")
```

### Example 2

```{r}
#lines <- readLines("./ae2_data_wrong2.json")
#lines[4]
```

```{r error=TRUE}
#transform(
#  all_table_filenames = all_table_filenames,
#  all_feature_json_filenames = "./ae2_data_wrong2.json")
```

### Example 3

```{r}
#lines <- readLines("./ae2_data_wrong3.json")
#lines[11]
```

```{r error=TRUE}
#transform(
#  all_table_filenames = all_table_filenames,
#  all_feature_json_filenames = "./ae2_data_wrong3.json")
```

