on:
  push:
    branches: [main]

name: Publish docs

# workflow must have permissions to push to gh-pages branch
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::pkgdown
            any::rmarkdown
            any::knitr
            any::kableExtra
            any::tidyverse
            any::lintr

      - name: Build package docs
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy built files to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
